name: Github Upload Task
on: 
    push:
        branches:
        - master
        paths-ignore:
        - 'README.md'
        - 'LICENSE'
        - '.gitignore'
jobs:
    build:
        env:
          ACTIONS_STEP_DEBUG: true

        runs-on: ubuntu-22.04
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 3

        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - uses: pnpm/action-setup@v2
          with:
            version: 8
        - uses: actions/setup-python@v4
          with:
            python-version: '>=3.11'
            architecture: 'x64'
        
        - name: List Files
          run: ls -R

        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        
        - name: Setting up Python environment
          run: |
            python -m pip install --upgrade pip
            python -m venv .venv
        
        - name: Activate Python environment
          run: source .venv/bin/activate

        - name: Install Python dependencies
          run: pip install -r requirements.txt
        
        - name: Running Python script
          run: python main.py

        - name: Push checksums to GitHub
          uses: github-actions-x/commit@v2.9
          with:
            files: |
              checksums.json
            name: 'GitHub Actions Bot'
            push-branch: 'master'
            commit-message: 'Update checksums.json'
            github-token: ${{ secrets.GITHUB_TOKEN }}
